@startuml

title Состояния программы

[*] --> Начало_программы
Начало_программы --> Загрузка_данных
Загрузка_данных --> Вывод_первого_меню
Вывод_первого_меню --> Завершение_программы
Вывод_первого_меню --> Вывод_информации_о_группах
Вывод_первого_меню --> Регистрация_в_детском_саду
Вывод_первого_меню --> Начать_день_в_детском_саду
Вывод_первого_меню --> Исключение_из_детского_сада
Вывод_первого_меню --> Сохранить_изменения

Начать_день_в_детском_саду --> Вывод_второго_меню
Вывод_второго_меню --> Учебные_занятия
Вывод_второго_меню --> Развивающие_игры
Вывод_второго_меню --> Приём_пищи
Вывод_второго_меню --> Дневной_сон
Вывод_второго_меню --> Завершить_день


Завершить_день --> Вывод_первого_меню

Завершение_программы --> [*]

state Набор_детей{
    [*] --> Вывод_списка_группы
    Вывод_списка_группы --> Выберите_ребенка_или_введите_0_для_завершения
    Выберите_ребенка_или_введите_0_для_завершения --> Выбор_завершен
    Выберите_ребенка_или_введите_0_для_завершения --> Этот_ребенок_уже_выбран
    Выберите_ребенка_или_введите_0_для_завершения --> Добавление
    Добавление --> Выберите_ребенка_или_введите_0_для_завершения
    Этот_ребенок_уже_выбран --> Выберите_ребенка_или_введите_0_для_завершения
    Выбор_завершен --> Сначала_выберите_детей

}

state Регистрация_в_детском_саду {
    [*] --> Ввод_номера_группы_для_регистрации
    Ввод_номера_группы_для_регистрации --> В_данной_группе_все_места_заняты
    Ввод_номера_группы_для_регистрации --> Ребенок_не_подходит_по_возрасту_в_эту_группу
    Ввод_номера_группы_для_регистрации --> Ребенок_успешно_зарегестрирован
    В_данной_группе_все_места_заняты --> Вывод_первого_меню
    Ребенок_не_подходит_по_возрасту_в_эту_группу --> Вывод_первого_меню
    Ребенок_успешно_зарегестрирован --> Вывод_первого_меню
}

state Исключение_из_детского_сада {
    [*] --> Ввод_номера_группы_для_исключения
    Ввод_номера_группы_для_исключения --> Ребенок_не_найден
    Ввод_номера_группы_для_исключения --> Ребенок_успешно_исключен
    Ребенок_не_найден --> Вывод_первого_меню
    Ребенок_успешно_исключен --> Вывод_первого_меню
}

state Учебные_занятия {
    [*] --> Набор_детей
    Набор_детей --> Вывод_списка_учебных_материалов
    Вывод_списка_учебных_материалов --> Ввод_номера_учебного_материала
    Ввод_номера_учебного_материала --> Вывод_информации_о_развитии_навыка_у_ребенка
    Ввод_номера_учебного_материала --> Ребенок_мал_для_изучения_таких_материалов
    Ввод_номера_учебного_материала --> Ребенок_слишком_устал_для_занятий
    Ввод_номера_учебного_материала --> Завершение_учебных_занятий
    Вывод_информации_о_развитии_навыка_у_детей --> Набор_детей
    Ребенок_мал_для_изучения_таких_материалов --> Набор_детей
    Ребенок_слишком_устал_для_занятий --> Набор_детей
    Завершение_учебных_занятий --> Вывод_второго_меню

}

state  Развивающие_игры{
    [*] --> Набор_детей
    Набор_детей --> Вывод_списка_развивающих_игр
    Вывод_списка_развивающих_игр --> Ввод_номера_игры
    Вывод_списка_развивающих_игр --> Вывод_информации_о_развитии_навыка_у_ребенка
    Вывод_списка_развивающих_игр --> Ребенок_слишком_голоден_для_игр
    Ввод_номера_игры --> Завершение_развивающих_игр
    Вывод_информации_о_развитии_навыка_у_детей --> Набор_детей
    Ребенок_слишком_голоден_для_игр --> Набор_детей
    Завершение_развивающих_игр --> Вывод_второго_меню

}

state Приём_пищи{
    [*] --> Ребенок_ест
    [*] --> Ребенок_не_голоден
    Ребенок_ест --> Вывод_второго_меню
    Ребенок_не_голоден --> Вывод_второго_меню
}

state Дневной_сон{
    [*] --> Ребенок_спит
    [*] --> Ребенок_не_сонный
    Ребенок_спит --> Вывод_второго_меню
    Ребенок_не_сонный --> Вывод_второго_меню
}

state Начать_день_в_детском_саду{
    [*] --> Вывод_приветствия_воспитателя_с_родителем
    Вывод_приветствия_воспитателя_с_родителем --> Вывод_второго_меню
}

state Завершить_день{
    [*] --> Вывод_прощания_воспитателя_с_ребенком
    Вывод_прощания_воспитателя_с_ребенком --> Вывод_уровня_навыков_ребенка_для_родителя
    Вывод_уровня_навыков_ребенка_для_родителя --> Вывод_первого_меню
}

@enduml