@startuml

title Состояния программы

[*] --> Начало_программы
Начало_программы --> Загрузка_данных
Загрузка_данных --> Вывод_первого_меню
Вывод_первого_меню --> Завершение_программы
Вывод_первого_меню --> Вывод_информации_о_группах
Вывод_первого_меню --> Регистрация_в_детском_саду
Вывод_первого_меню --> Начать_день_в_детском_саду
Вывод_первого_меню --> Исключение_из_детского_сада
Вывод_первого_меню --> Сохранить_изменения

Начать_день_в_детском_саду --> Вывод_второго_меню
Вывод_второго_меню --> Учебные_занятия
Вывод_второго_меню --> Развивающие_игры
Вывод_второго_меню --> Приём_пищи
Вывод_второго_меню --> Дневной_сон
Вывод_второго_меню --> Завершить_день

Завершить_день --> Вывод_первого_меню

Завершение_программы --> [*]

state Регистрация_в_детском_саду {
    [*] --> Ввод_номера_группы
    Ввод_номера_группы --> В_данной_группе_все_места_заняты
    Ввод_номера_группы --> Ребенок_не_подходит_по_возрасту_в_эту_группу
    Ввод_номера_группы --> Ребенок_успешно_зарегестрирован
    В_данной_группе_все_места_заняты --> Вывод_первого_меню
    Ребенок_не_подходит_по_возрасту_в_эту_группу --> Вывод_первого_меню
    Ребенок_успешно_зарегестрирован --> Вывод_первого_меню
}

@enduml